name: device-tree-compiler
version: '1.5.1'
summary: Device Tree Compiler
description: |
  Device Tree Compiler, dtc, takes as input a device-tree in a given format
  and outputs a device-tree in another format for booting kernels on embedded
  systems.  Typically, the input format is "dts", a human readable source
  format, and creates a "dtb", or binary format as output.

grade: stable
confinement: strict
base: core18

apps:
  convert-dtsv0:
    command: bin/convert-dtsv0
    plugs: [ home ]
  dtc:
    command: bin/dtc
    plugs: [ home ]
  dtdiff:
    command: bin/dtdiff
    plugs: [ home ]
  fdtdump:
    command: bin/fdtdump
    plugs: [ home ]
  fdtget:
    command: bin/fdtget
    plugs: [ home ]
  fdtoverlay:
    command: bin/fdtoverlay
    plugs: [ home ]
  fdtput:
    command: bin/fdtput
    plugs: [ home ]

parts:
  dtc:
    plugin: make
    source: https://git.kernel.org/pub/scm/utils/dtc/dtc.git/snapshot/dtc-1.5.1.tar.gz
    build-packages:
      - bison
      - flex
      - libyaml-dev
      - pkg-config
    artifacts:
      - convert-dtsv0
      - dtc
      - dtdiff
      - fdtdump
      - fdtget
      - fdtoverlay
      - fdtput
      - libfdt/libfdt-1.5.0.so
      - libfdt/libfdt.so.1
    organize:
      convert-dtsv0: bin/convert-dtsv0
      dtc: bin/dtc
      dtdiff: bin/dtdiff
      fdtdump: bin/fdtdump
      fdtget: bin/fdtget
      fdtoverlay: bin/fdtoverlay
      fdtput: bin/fdtput
      libfdt/libfdt-1.5.0.so: lib/libfdt-1.5.0.so
      libfdt/libfdt.so.1: lib/libfdt.so.1
    override-prime: |
      snapcraftctl prime
      rmdir libfdt
      chmod +x bin/dtdiff
