name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Snap package
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Run snapcraft
      uses: snapcore/action-build@v1
      id: snapcraft

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}

  test:
    name: Test Snap package
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: snap

    - name: Install Snap package
      run: |
        sudo snap install --classic --dangerous snap/*.snap

    - name: Run to verify commands
      run: |
        device-tree-compiler.convert-dtsv0 --version
        device-tree-compiler.dtc --version
        device-tree-compiler.fdtdump --version
        device-tree-compiler.fdtget --version
        device-tree-compiler.fdtoverlay --version
        device-tree-compiler.fdtput --version
